version: "3.7"
services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      args:
        XDEBUG_REMOTE_HOST: ${DOCKER_HOST_IP}
    container_name: ${DOCKER_PREFIX}php
    environment:
      PHP_IDE_CONFIG: serverName=erp
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - net

networks:
  net:
    name: ${DOCKER_NETWORK_NAME}
    ipam:
      driver: default
      config:
        - subnet: "${DOCKER_SUBNET}"

volumes:
  data: {}